# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
  locale: '%env(string:LOCALE)%'

  votix_secret:          '%env(string:VOTIX_SECRET)%'
  votix_key_secret:      '%env(string:VOTIX_KEY_SECRET)%'

  # celui là sera transmis au BDE
  votix_result_password: '%env(string:VOTIX_RESULT_PASSWORD)%'

  votix_link_base:       https://%env(string:HOSTNAME)%/vote/

  # http://www.timestamp.fr/
  votix_start:   '%env(int:VOTIX_START)%'
  votix_end:     '%env(int:VOTIX_END)%'
  votix_support: '%env(string:VOTIX_SUPPORT)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $votixStart: '%votix_start%'
      $votixEnd: '%votix_end%'
      $archiveFile: '%kernel.root_dir%/../var/halloffame.yml'
      $keysDirectory: '%kernel.root_dir%/../var'
      $secretKey: '%votix_key_secret%'
      $secret: '%votix_secret%'
      $salt: '%votix_secret%'
      $linkBase: '%votix_link_base%'
      $password: '%votix_result_password%'

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: '../src/*'
    exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

  App\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']

  Aws\Ses\SesClient:
    arguments:
      $args:
        key: 'dwe'
        secret: 'dwewd'
        region: 'eu-west-1'
        # https://docs.aws.amazon.com/aws-sdk-php/v3/api/class-Aws.Ses.SesClient.html
        version: '2010-12-01'
